#############################################################################
# Makefile for building: mymeego
# Generated by qmake (2.01a) (Qt 4.7.2) on: Mon Apr 4 13:05:28 2011
# Project:  mymeego.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile mymeego.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/olli/rawdimension/ui/src/src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/olli/rawdimension/ui/src/src.pro -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: mymeego.pro  /opt/qt4/share/mkspecs/linux-g++/qmake.conf /opt/qt4/share/mkspecs/common/g++.conf \
		/opt/qt4/share/mkspecs/common/unix.conf \
		/opt/qt4/share/mkspecs/common/linux.conf \
		/opt/qt4/share/mkspecs/qconfig.pri \
		/opt/qt4/share/mkspecs/features/qt_functions.prf \
		/opt/qt4/share/mkspecs/features/qt_config.prf \
		/opt/qt4/share/mkspecs/features/exclusive_builds.prf \
		/opt/qt4/share/mkspecs/features/default_pre.prf \
		/opt/qt4/share/mkspecs/features/release.prf \
		/opt/qt4/share/mkspecs/features/default_post.prf \
		/opt/qt4/share/mkspecs/features/warn_on.prf \
		/opt/qt4/share/mkspecs/features/qt.prf \
		/opt/qt4/share/mkspecs/features/unix/thread.prf \
		/opt/qt4/share/mkspecs/features/moc.prf \
		/opt/qt4/share/mkspecs/features/resources.prf \
		/opt/qt4/share/mkspecs/features/uic.prf \
		/opt/qt4/share/mkspecs/features/yacc.prf \
		/opt/qt4/share/mkspecs/features/lex.prf \
		/opt/qt4/share/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile mymeego.pro
/opt/qt4/share/mkspecs/common/g++.conf:
/opt/qt4/share/mkspecs/common/unix.conf:
/opt/qt4/share/mkspecs/common/linux.conf:
/opt/qt4/share/mkspecs/qconfig.pri:
/opt/qt4/share/mkspecs/features/qt_functions.prf:
/opt/qt4/share/mkspecs/features/qt_config.prf:
/opt/qt4/share/mkspecs/features/exclusive_builds.prf:
/opt/qt4/share/mkspecs/features/default_pre.prf:
/opt/qt4/share/mkspecs/features/release.prf:
/opt/qt4/share/mkspecs/features/default_post.prf:
/opt/qt4/share/mkspecs/features/warn_on.prf:
/opt/qt4/share/mkspecs/features/qt.prf:
/opt/qt4/share/mkspecs/features/unix/thread.prf:
/opt/qt4/share/mkspecs/features/moc.prf:
/opt/qt4/share/mkspecs/features/resources.prf:
/opt/qt4/share/mkspecs/features/uic.prf:
/opt/qt4/share/mkspecs/features/yacc.prf:
/opt/qt4/share/mkspecs/features/lex.prf:
/opt/qt4/share/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile mymeego.pro

qmake_all: sub-src-qmake_all FORCE

make_default: sub-src-make_default FORCE
make_first: sub-src-make_first FORCE
all: sub-src-all FORCE
clean: sub-src-clean FORCE
distclean: sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

sub-src-check: src/$(MAKEFILE)
	cd src/ && $(MAKE) check
check: sub-src-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install_CONF: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/mymeego/conf/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/mymeego/conf/ 
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/conf/coherence.conf $(INSTALL_ROOT)/usr/share/mymeego/conf/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/conf/coherence2.conf $(INSTALL_ROOT)/usr/share/mymeego/conf/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/conf/mymeego.conf $(INSTALL_ROOT)/usr/share/mymeego/conf/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/conf/mymeego_car.conf $(INSTALL_ROOT)/usr/share/mymeego/conf/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/conf/mymeego_netbook.conf $(INSTALL_ROOT)/usr/share/mymeego/conf/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/conf/mymeego_tv.conf $(INSTALL_ROOT)/usr/share/mymeego/conf/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/conf/test.conf $(INSTALL_ROOT)/usr/share/mymeego/conf/


uninstall_CONF:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/conf/coherence.conf 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/conf/coherence2.conf 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/conf/mymeego.conf 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/conf/mymeego_car.conf 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/conf/mymeego_netbook.conf 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/conf/mymeego_tv.conf 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/conf/test.conf
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/mymeego/conf/ 


install_DAEMON: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/mymeego/scripts/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/mymeego/scripts/ 
	-$(INSTALL_PROGRAM) /home/olli/rawdimension/ui/daemon/Agent.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/
	-strip $(INSTALL_ROOT)/usr/share/mymeego/scripts/Agent.py
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/daemon/BackendDevice.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/daemon/BackendUpnp.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/daemon/Config.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/daemon/EventHandler.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/
	-$(INSTALL_PROGRAM) /home/olli/rawdimension/ui/daemon/main.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/
	-strip $(INSTALL_ROOT)/usr/share/mymeego/scripts/main.py
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/daemon/Module.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/
	-$(INSTALL_PROGRAM) /home/olli/rawdimension/ui/daemon/test.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/
	-strip $(INSTALL_ROOT)/usr/share/mymeego/scripts/test.py
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/daemon/TransferList.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/daemon/XmlData.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/daemon/XmlGenerator.py $(INSTALL_ROOT)/usr/share/mymeego/scripts/


uninstall_DAEMON:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/Agent.py 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/BackendDevice.py 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/BackendUpnp.py 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/Config.py 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/EventHandler.py 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/main.py 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/Module.py 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/test.py 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/TransferList.py 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/XmlData.py 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/mymeego/scripts/XmlGenerator.py
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/mymeego/scripts/ 


install_BACKEND: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/conf/mymeego-backend $(INSTALL_ROOT)/usr/bin/


uninstall_BACKEND:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/bin/mymeego-backend
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_SERVICE: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/dbus-1/services/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/dbus-1/services/ 
	-$(INSTALL_FILE) /home/olli/rawdimension/ui/conf/org.mymeego.Backend $(INSTALL_ROOT)/usr/share/dbus-1/services/


uninstall_SERVICE:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dbus-1/services/org.mymeego.Backend
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/dbus-1/services/ 


install: install_subtargets install_CONF install_DAEMON install_BACKEND install_SERVICE  FORCE

uninstall: uninstall_CONF uninstall_DAEMON uninstall_BACKEND uninstall_SERVICE  uninstall_subtargets FORCE

FORCE:

